[package]
name = "bevy_toasts"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", default-features = false, features = ["bevy_ui", "bevy_text", "default_font"] }
anyhow = "1.0"

[dev-dependencies]
bevy_editor_pls = "*"

[[example]]
name = "toasts"
path = "examples/toasts.rs"
required-features = ["bevy/bevy_winit", "bevy/x11"]
